### ISSUE TITLE
사용자 신용점수 조회 및 상품 안내

### ISSUE THREAD

**Issue by JaeIL00** [ujutechnology/MINI-88-FE#1]
## Description
사용자의 신용점수를 표시하고 신용 점수 기반으로 상품 이율을 반영해 조회한다.

## To-do
- [x] 신용점수 조회 퍼블리싱
- [ ] Api 사용자 데이터 받아오기 (신용 등급, 신용자 구분)
- [x] Api 상품 데이터 받아오기(상품 이름, 기업 이름, 기업 이미지, 이율)
- [ ] Api 유저 포인트 이율 반영
- [x] 상품 카테고리 조회 퍼블리싱
- [ ] 상품 카테고리 필터링
- [ ] 상품 한도 확인 로직
