### ISSUE TITLE
페이지 라우팅

### ISSUE THREAD

**Issue by Mangrove-Sun** [ujutechnology/MINI-88-FE#10]
## Description

- 각각의 페이지에 URL을 매핑한다.

## To-do

- [x] 맞춤형 상품(Home)
- [x] 금융 상품(AllProduct)
- [x] 신용등급 테스트(CreditScore)
- [x] 장바구니(Cart)
- [x] 마이프로필(Profile)
- [x] 회원가입(Signup)
- [x] 로그인(Signin)
- [x] 온보딩(OnBoarding)

**Comment by Mangrove-Sun** [comment]
main 브랜치로 Merge 되었습니다.
