### ISSUE TITLE
금융 상품

### ISSUE THREAD

**Issue by Mangrove-Sun** [ujutechnology/MINI-88-FE#12]
## Description

전체 상품을 보여준다.

## To-do

- [x] Api 상품 리스트 데이터 요청 로직 작성
- [ ] IntersectionObserver를 사용해 다음 데이터 요청 로직 구현
- [x] 응답받은 데이터로 상품 카드 생성 및 출력
