### ISSUE TITLE
바텀 네비게이션

### ISSUE THREAD

**Issue by Mangrove-Sun** [ujutechnology/MINI-88-FE#15]
## Description

사용자가 어플리케이션의 기능을 쉽게 사용할 수 있게 만들어주는 네비게이션을 작성한다.

## To-do

- [x] 네비게이션 탭을 누르면 해당 페이지로 이동할 수 있게 한다.
- [x] 바텀 네비게이션이 필요한 페이지에서만 표시되도록 구현한다.
- [x] 사용자 선택한 탭이 무엇인지 쉽게 알아볼 수 있게 구현한다.
