### ISSUE TITLE
장바구니(찜하기)

### ISSUE THREAD

**Issue by JaeIL00** [ujutechnology/MINI-88-FE#3]
## Description
사용자가 신청하기 원하거나 관심있는 상품을 보관하고 신청한다.

## To-do
- [ ] 상품 찜하기 퍼블리싱
- [ ] Api 사용자 찜 데이터 요청
- [ ] 대출(상품) 신청 퍼블리싱
- [ ] Api 사용자 대출신청 입력?
